### ISSUE TITLE
catch ctrl-c

### ISSUE THREAD

**Issue by dmalan** [cs50/render50#45]
```
$ render50 -o lecture5.pdf * -x "*" --include "*.html" -i "*.js" -i "*.vue"
^CSorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.0/bin/render50", line 501, in <module>
    from weasyprint import CSS, HTML
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/__init__.py", line 376, in <module>
    from .html import (
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/html.py", line 47, in <module>
    HTML5_UA_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ua.css'))
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/__init__.py", line 278, in __init__
    self.page_rules, self.fonts, font_config)
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 679, in preprocess_stylesheet
    base_url, tinycss2.parse_declaration_list(rule.content)))
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/css/validation.py", line 2232, in preprocess_declarations
    result = list(expander_(base_url, name, tokens))
  File "/opt/pyenv/versions/3.7.0/lib/python3.7/site-packages/weasyprint/css/validation.py", line 2164, in validate_non_shorthand
    if function.wants_base_url:
KeyboardInterrupt
```

**Comment by dmalan** [comment]
https://github.com/cs50/render50/commit/2d1507e0cd43ccf2d90299466be650da152807cf
